server:
  port: 8000

spring:
  application:
    name: huiyu-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: huiyu-auth
          uri: lb://huiyu-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8100/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
