server:
  port: 8000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:3333
    gateway:
      routes:
        - id: huiyu-auth
          uri: lb://huiyu-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: huiyu-service
          uri: lb://huiyu-service
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:${server.port}/auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    host: localhost
    port: 6378
    password: 123asdASD
    database: 0
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"

logging:
  level:
    root: info
    com.huiyu: debug
