server:
  port: 8010

spring:
  application:
    name: huiyu-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.14.157:3333
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.14.157:3306/huiyu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: huiyu
    password: hnv2qJxDmL_5AUtuHK
    druid:
      #initialSize: 10
      #minIdle: 10
      #maxActive: 10
      # 监控配置
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        enabled: true
        allow:
      # 监控配置中的 web监控
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        enabled: true
  redis:
    host: 101.43.14.157
    port: 6378
    password: 123asdASD
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-enum-type-handler: com.huiyu.service.core.handler.EnumTypeHandle

logging:
  level:
    root: info
    com.huiyu: debug

huiyu:
  sd:
    callback-token: LGVMAXk38rZmfwo1Qzf6jl7TcdoCqT97
