scrape_configs:
  - job_name: 'springboot-prometheus-example' # 任务名称随便写
    metrics_path: '/actuator/prometheus'    # 采集的路径
    static_configs:
      - targets: [ '127.0.0.1:8010' ]    # ip和端口写自己springboot应用的
